'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { addTeacher, deactivateTeacher, getClasses, getSubjects, getTeachers, updateTeacher } from '@/services/schoolService';
import { SectionHeader, TableSkeleton } from '@/components/ui/index';
import toast from 'react-hot-toast';

const err=e=>e?.response?.data?.error?.message||e?.message||'Request failed';
const empty={name:'',mobile:'',email:'',employeeId:'',designation:'Teacher',qualification:'',experienceYears:0,employmentType:'FULL_TIME',assignments:[]};

export default function SchoolTeachersPage(){
 const qc=useQueryClient();const [show,setShow]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(empty);const [credential,setCredential]=useState(null);
 const teachersQ=useQuery({queryKey:['school-teachers'],queryFn:()=>getTeachers().then(r=>r.data.data||[])});
 const classesQ=useQuery({queryKey:['school-classes'],queryFn:()=>getClasses().then(r=>r.data.data||[])});
 const subjectsQ=useQuery({queryKey:['school-subjects'],queryFn:()=>getSubjects().then(r=>r.data.data||[])});
 const teachers=teachersQ.data||[],classes=classesQ.data||[],subjects=subjectsQ.data||[];
 const save=useMutation({mutationFn:()=>editing?updateTeacher(editing.id,form):addTeacher(form),onSuccess:async res=>{const d=res.data.data;if(!editing&&d.temporaryPassword)setCredential({name:d.name,username:d.username,password:d.temporaryPassword});toast.success(editing?'Teacher updated':'Teacher added');setShow(false);setEditing(null);setForm(empty);await Promise.all([qc.invalidateQueries({queryKey:['school-teachers']}),qc.invalidateQueries({queryKey:['school-overview']})]);},onError:e=>toast.error(err(e))});
 const deactivate=useMutation({mutationFn:deactivateTeacher,onSuccess:async()=>{toast.success('Teacher deactivated');await qc.invalidateQueries({queryKey:['school-teachers']});},onError:e=>toast.error(err(e))});
 function addAssignment(){if(!classes[0]||!subjects[0])return toast.error('Configure a class and subject first');setForm(f=>({...f,assignments:[...(f.assignments||[]),{classId:classes[0].id,subjectCode:subjects[0].code,isClassTeacher:false}]}));}
 function setAssignment(i,key,value){setForm(f=>({...f,assignments:f.assignments.map((a,x)=>x===i?{...a,[key]:value}:a)}));}
 function startEdit(t){setEditing(t);setForm({name:t.name,mobile:t.mobile,email:t.email||'',employeeId:t.employee_id||'',designation:t.designation||'Teacher',qualification:t.qualification||'',experienceYears:t.experience_yrs||0,employmentType:t.employment_type||'FULL_TIME',status:t.status,assignments:(t.assignments||[]).map(a=>({classId:a.classId,subjectCode:a.subjectCode,isClassTeacher:a.isClassTeacher}))});setShow(true);}
 return <div className="animate-fade-up">
  <SectionHeader title="👩‍🏫 Teacher Management" sub={`${teachers.filter(x=>x.status==='ACTIVE').length} active teachers`}><button className="btn-primary" onClick={()=>{setEditing(null);setForm(empty);setShow(v=>!v)}}>+ Add Teacher</button></SectionHeader>
  {credential&&<div className="card mb-5" style={{border:'2px solid var(--forest)',background:'var(--forest-pale)'}}><div className="font-display font-bold" style={{color:'var(--forest)'}}>Teacher account created</div><div className="text-sm mt-2"><b>{credential.name}</b> · Username: <code>{credential.username}</code> · Temporary password: <code>{credential.password}</code></div><p className="text-xs mt-1" style={{color:'var(--slate)'}}>Share this securely. The Teacher will be asked to manage their password after login.</p><button className="text-xs font-bold mt-2" onClick={()=>setCredential(null)}>Dismiss</button></div>}
  {show&&<div className="card mb-5" style={{border:'2px solid var(--saffron)'}}><h3 className="font-display font-bold mb-4" style={{color:'var(--navy)'}}>{editing?'Edit Teacher':'Add Teacher'}</h3><div className="grid md:grid-cols-2 gap-3"><input className="input" placeholder="Full name *" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><input className="input" placeholder="10-digit mobile *" maxLength={10} value={form.mobile} onChange={e=>setForm(f=>({...f,mobile:e.target.value.replace(/\D/g,'')}))}/><input className="input" type="email" placeholder="Email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/><input className="input" placeholder="Employee ID" value={form.employeeId} onChange={e=>setForm(f=>({...f,employeeId:e.target.value}))}/><input className="input" placeholder="Designation" value={form.designation} onChange={e=>setForm(f=>({...f,designation:e.target.value}))}/><input className="input" placeholder="Qualification" value={form.qualification} onChange={e=>setForm(f=>({...f,qualification:e.target.value}))}/><input type="number" min="0" max="60" className="input" placeholder="Experience years" value={form.experienceYears} onChange={e=>setForm(f=>({...f,experienceYears:Number(e.target.value)}))}/><select className="input select" value={form.employmentType} onChange={e=>setForm(f=>({...f,employmentType:e.target.value}))}>{['FULL_TIME','PART_TIME','CONTRACT','VISITING'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select>{editing&&<select className="input select" value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{['ACTIVE','ON_LEAVE','INACTIVE'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select>}</div>
   <div className="mt-5 flex items-center justify-between"><h4 className="font-display font-bold" style={{color:'var(--navy)'}}>Class & Subject Assignments</h4><button className="btn-ghost text-xs" onClick={addAssignment}>+ Assignment</button></div><div className="space-y-2 mt-2">{(form.assignments||[]).map((a,i)=><div key={i} className="grid sm:grid-cols-[1fr_1fr_auto_auto] gap-2 items-center p-3 rounded-xl" style={{background:'#F7F8FA'}}><select className="input select" value={a.classId} onChange={e=>setAssignment(i,'classId',e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>Class {c.class_name}-{c.section}</option>)}</select><select className="input select" value={a.subjectCode} onChange={e=>setAssignment(i,'subjectCode',e.target.value)}>{subjects.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select><label className="text-xs flex items-center gap-1"><input type="checkbox" checked={!!a.isClassTeacher} onChange={e=>setAssignment(i,'isClassTeacher',e.target.checked)}/> Class teacher</label><button className="text-xs" style={{color:'#C62828'}} onClick={()=>setForm(f=>({...f,assignments:f.assignments.filter((_,x)=>x!==i)}))}>Remove</button></div>)}</div>
   <div className="flex gap-2 mt-4"><button className="btn-primary" disabled={save.isPending||!form.name||form.mobile.length!==10} onClick={()=>save.mutate()}>{save.isPending?'Saving…':'Save Teacher'}</button><button className="btn-ghost" onClick={()=>setShow(false)}>Cancel</button></div>
  </div>}
  <div className="card">{teachersQ.isLoading?<TableSkeleton rows={5} cols={7}/>:<div className="overflow-x-auto"><table className="tbl"><thead><tr><th>Employee</th><th>Name</th><th>Designation</th><th>Assignments</th><th>Mobile</th><th>Status</th><th>Action</th></tr></thead><tbody>{teachers.map(t=><tr key={t.id}><td>{t.employee_id||'—'}</td><td><b>{t.name}</b><div className="text-xs" style={{color:'var(--slate)'}}>@{t.username}</div></td><td>{t.designation||'Teacher'}</td><td className="text-xs">{(t.assignments||[]).map(a=>`${a.className}-${a.section} ${a.subjectCode}`).join(', ')||'—'}</td><td>{t.mobile}</td><td><span className={`badge ${t.status==='ACTIVE'?'badge-green':t.status==='ON_LEAVE'?'badge-orange':'badge-red'}`}>{t.status}</span></td><td><div className="flex gap-2"><button className="text-xs font-bold" style={{color:'var(--saffron)'}} onClick={()=>startEdit(t)}>Edit</button>{t.status!=='INACTIVE'&&<button className="text-xs font-bold" style={{color:'#C62828'}} disabled={deactivate.isPending} onClick={()=>{if(confirm(`Deactivate ${t.name}?`))deactivate.mutate(t.id)}}>Deactivate</button>}</div></td></tr>)}</tbody></table>{!teachers.length&&<div className="py-10 text-center" style={{color:'var(--slate)'}}>No Teachers yet.</div>}</div>}</div>
 </div>;
}
