import { Router, type RequestHandler } from 'express';
import { z } from 'zod';
import { authenticate, authorize } from '../middleware/auth.middleware';
import { validate } from '../middleware/validate.middleware';
import * as service from '../services/syllabus.service';
import * as R from '../utils/response';
const httpsUrl=z.string().url().max(2000).refine(v=>{try {const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}},'Use an HTTPS evidence URL');
const year=z.string().regex(/^20\d{2}-\d{2}$/).refine(v=>Number(v.slice(5))===(Number(v.slice(0,4))+1)%100,'Academic year must be consecutive, such as 2026-27');
const grade=z.string().regex(/^(PRE_NURSERY|NURSERY|LKG|UKG|CLASS_([1-9]|1[0-2]))$/);
const route=(fn:(req:any)=>Promise<unknown>):RequestHandler=>async(req,res,next)=>{try{return R.ok(res,await fn(req));}catch(e){next(e);}};
export const adminSyllabusRoutes=Router();
adminSyllabusRoutes.use(authenticate,authorize('SUPER_ADMIN'));
adminSyllabusRoutes.get('/options',route(()=>service.syllabusOptions()));
adminSyllabusRoutes.post('/import',validate(z.object({boardCode:z.string().min(2).max(30),academicYear:year,title:z.string().trim().min(3).max(180),sourceUrl:httpsUrl,rows:z.array(z.object({gradeCode:grade,subjectId:z.string().uuid(),chapter:z.string().trim().min(1).max(220),topic:z.string().trim().min(1).max(220),topicHi:z.string().trim().max(220).optional(),learningOutcome:z.string().trim().min(3).max(2000),evidenceUrl:httpsUrl,pageReference:z.string().trim().min(1).max(100)})).min(1).max(500)})),route(req=>service.importSyllabus(req.body,req.user.userId)));
adminSyllabusRoutes.patch('/topics/:id',validate(z.object({id:z.string().uuid()}),'params'),validate(z.object({retired:z.boolean(),note:z.string().trim().min(10).max(2000)})),route(req=>service.retireSyllabusTopic(req.params.id,req.body.retired,req.body.note,req.user.userId)));
adminSyllabusRoutes.post('/topics/:id/resources',validate(z.object({id:z.string().uuid()}),'params'),validate(z.object({resourceId:z.string().uuid()})),route(req=>service.linkTopicResource(req.params.id,req.body.resourceId,req.user.userId)));
adminSyllabusRoutes.get('/:id',validate(z.object({id:z.string().uuid()}),'params'),route(req=>service.syllabusDetail(req.params.id)));
adminSyllabusRoutes.patch('/:id/status',validate(z.object({id:z.string().uuid()}),'params'),validate(z.object({status:z.enum(['DRAFT','ACTIVE','ARCHIVED']),note:z.string().trim().min(10).max(2000)})),route(req=>service.changeSyllabusStatus(req.params.id,req.body.status,req.body.note,req.user.userId)));
export const studentSyllabusRoutes=Router();
studentSyllabusRoutes.use(authenticate,authorize('STUDENT'));
studentSyllabusRoutes.get('/',route(req=>service.studentSyllabus(req.user.userId)));
studentSyllabusRoutes.put('/profile',validate(z.object({boardCode:z.string().min(2).max(30),gradeCode:grade,academicYear:year,language:z.enum(['en','hi'])})),route(req=>service.saveLearningPreference(req.user.userId,req.body)));
