import PublicModulePage, { type PublicModuleConfig } from '@/components/public/PublicModulePage';

const CONFIG: PublicModuleConfig = {
  eyebrow: 'For Parents & Guardians',
  title: 'Understand the child journey with',
  accentTitle: 'clear school-connected visibility',
  summary: 'VidyaSetu gives parents one protected place to see linked children, attendance, academic performance, report cards, fees, school notifications, teacher communication and moderated parent Groups.',
  audience: 'parents',
  loginRole: 'parent',
  metrics: [
    { key: 'parents', label: 'Active parent accounts' },
    { key: 'students', label: 'Active students' },
    { key: 'schools', label: 'Active schools' },
    { key: 'groups', label: 'Active Groups' },
  ],
  capabilities: [
    {
      icon: '👨‍👩‍👧',
      title: 'Linked children in one account',
      description: 'A parent can have more than one child linked and switch between each child’s school-connected information.',
      bullets: ['Multiple child links', 'School and class context', 'Protected family access'],
    },
    {
      icon: '📊',
      title: 'Performance tracking',
      description: 'Parents can review academic performance views rather than waiting only for periodic paper updates.',
      bullets: ['Recent performance', 'Subject-level visibility', 'Progress context over time'],
    },
    {
      icon: '📅',
      title: 'Attendance visibility',
      description: 'School attendance records are surfaced to the linked parent account with summary and detail views.',
      bullets: ['Attendance percentage', 'Present / absent / late states', 'Child-specific records'],
    },
    {
      icon: '📄',
      title: 'Report cards and results',
      description: 'Parents can open report-card information for a linked child without requiring access to the School Admin workspace.',
      bullets: ['Exam result visibility', 'Subject marks', 'Report-card access'],
    },
    {
      icon: '💳',
      title: 'Fees and dues',
      description: 'The Parent module exposes fee invoices and child-specific fee information generated by the school.',
      bullets: ['Fee items', 'Paid and outstanding amounts', 'Due-date visibility'],
    },
    {
      icon: '💬',
      title: 'Teacher communication',
      description: 'Parents can identify the child’s teacher context and exchange messages from the Parent workspace.',
      bullets: ['Teacher lookup', 'Child-specific message thread', 'Protected school-family communication'],
    },
    {
      icon: '🔔',
      title: 'Notifications',
      description: 'School and platform notifications are collected in one Parent view with read-state tracking.',
      bullets: ['Notification inbox', 'Read/unread states', 'School-linked updates'],
    },
    {
      icon: '👥',
      title: 'Parent Groups',
      description: 'Parents can collaborate in moderated Groups where creation, membership and invitations follow explicit approval and consent rules.',
      bullets: ['Parent or mixed Group types', 'Owner/moderator controls', 'Invitation consent and reporting'],
    },
    {
      icon: '🏫',
      title: 'School context',
      description: 'The public platform can show institution-level school information while a parent’s personal child records remain behind authentication.',
      bullets: ['School identity', 'Child-school relationship', 'Public school discovery without private student data'],
    },
  ],
  steps: [
    { title: 'Sign in as Parent', description: 'Use the Parent account type so VidyaSetu loads only children linked to that parent identity.' },
    { title: 'Choose a child', description: 'Open the linked child whose attendance, results, fees or teacher communication you want to review.' },
    { title: 'Review school records', description: 'Check performance, attendance, report cards, fees and school notifications from one parent view.' },
    { title: 'Communicate and collaborate', description: 'Message the relevant teacher and use approved Groups for parent-to-parent or mixed collaboration.' },
  ],
  proofTitle: 'Parent capabilities already backed by current APIs',
  proofIntro: 'The Parent module is implemented around child-specific data access and protected school-family communication.',
  proofs: [
    { icon: '🧒', title: 'Child dashboard', description: 'Linked-child selection plus a child-specific dashboard and performance view.' },
    { icon: '📆', title: 'Attendance & report card', description: 'Dedicated endpoints for child attendance and report-card data.' },
    { icon: '💰', title: 'Fees', description: 'Child-specific fee information generated from school records.' },
    { icon: '📨', title: 'Messages & notifications', description: 'Teacher messaging and notification read-state flows for the Parent account.' },
  ],
  loginTitle: 'Login to Parent Dashboard',
  loginText: 'Children, results, attendance, fees and messages are private family records. Sign in as Parent to view only the children linked to your account.',
};

export default function ParentsPublicPage() {
  return <PublicModulePage config={CONFIG} />;
}
