-- ============================================================
-- 017_school_management_core.sql
-- School Management: staff identity, school profile, class lifecycle,
-- fee receipts and current-year operational metadata.
-- Safe to run after 014-016 and idempotent on repeat runs.
-- ============================================================

ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'TEACHER';

BEGIN;

ALTER TABLE schools ADD COLUMN IF NOT EXISTS board VARCHAR(50);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS affiliation_number VARCHAR(80);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS principal_name VARCHAR(120);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;

ALTER TABLE school_classes ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE teachers ADD COLUMN IF NOT EXISTS designation VARCHAR(120);
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS employment_type VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME';
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS email_official VARCHAR(180);

ALTER TABLE fee_payments ADD COLUMN IF NOT EXISTS receipt_number VARCHAR(50);
CREATE UNIQUE INDEX IF NOT EXISTS uq_fee_payments_receipt_number
  ON fee_payments(receipt_number) WHERE receipt_number IS NOT NULL;
CREATE SEQUENCE IF NOT EXISTS receipt_number_seq START WITH 100001;

-- Legacy development teacher accounts were originally stored as SCHOOL_ADMIN.
-- Promote only users that are actually linked to a teacher profile.
UPDATE users u
SET role = 'TEACHER'::user_role,
    updated_at = NOW()
WHERE EXISTS (SELECT 1 FROM teachers t WHERE t.user_id = u.id)
  AND u.role = 'SCHOOL_ADMIN'::user_role;

-- Keep operational school data on the current demo academic year without
-- touching future real-school records outside the two known seeded schools.
UPDATE teacher_assignments ta
SET academic_year = '2026-27'
WHERE ta.school_id IN (
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000002'
)
  AND ta.academic_year <> '2026-27';

UPDATE timetable_periods tp
SET academic_year = '2026-27', updated_at = NOW()
WHERE tp.school_id IN (
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000002'
)
  AND tp.academic_year <> '2026-27';

UPDATE fee_structures fs
SET academic_year = '2026-27', updated_at = NOW()
WHERE fs.school_id IN (
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000002'
)
  AND fs.academic_year <> '2026-27';

UPDATE fee_invoices fi
SET academic_year = '2026-27', updated_at = NOW()
WHERE fi.school_id IN (
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000002'
)
  AND fi.academic_year <> '2026-27';

-- Recompute every School, including Schools with zero Teacher rows.
UPDATE schools s
SET total_teachers = (
      SELECT COUNT(*)::INTEGER
      FROM teachers t
      WHERE t.school_id = s.id AND t.status = 'ACTIVE'
    ),
    updated_at = NOW();

COMMENT ON COLUMN schools.board IS 'School board, e.g. CBSE, ICSE, UP Board, State Board';
COMMENT ON COLUMN schools.affiliation_number IS 'Board affiliation/reference number when applicable';
COMMENT ON COLUMN school_classes.is_active IS 'Archived class-sections remain historically queryable but are hidden from active operations';
COMMENT ON COLUMN fee_payments.receipt_number IS 'Human-readable receipt identifier generated by School Management';

COMMIT;
