'use client';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { addStudent, bulkAddStudents, getClasses, getStudentDetail, getStudents, linkStudentParent, updateStudent } from '@/services/schoolService';
import { SectionHeader, StatusBadge, TableSkeleton } from '@/components/ui/index';
import useAuthStore from '@/store/authStore';
import toast from 'react-hot-toast';

const err=e=>e?.response?.data?.error?.message||e?.message||'Request failed';
const emptyStudent={name:'',mobile:'',email:'',classId:'',rollNumber:'',parentName:'',parentMobile:'',parentEmail:'',parentRelation:'PARENT'};

function downloadText(name,text){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function csvCell(v){return String(v??'').trim();}

export default function SchoolStudentsPage(){
 const {user}=useAuthStore();const canAdmin=['SCHOOL_ADMIN','SUPER_ADMIN'].includes(user?.role);
 const qc=useQueryClient();
 const [search,setSearch]=useState('');const [classId,setClassId]=useState('');const [page,setPage]=useState(1);
 const [showAdd,setShowAdd]=useState(false);const [form,setForm]=useState(emptyStudent);const [selectedId,setSelectedId]=useState(null);const [edit,setEdit]=useState(null);const [parent,setParent]=useState({name:'',mobile:'',email:'',relation:'PARENT'});const [bulkMessage,setBulkMessage]=useState('');
 const classesQ=useQuery({queryKey:['school-classes'],queryFn:()=>getClasses().then(r=>r.data.data||[])});const classes=classesQ.data||[];
 const studentsQ=useQuery({queryKey:['school-students',search,classId,page],queryFn:()=>getStudents({search,classId,page,limit:20}).then(r=>r.data),placeholderData:p=>p});
 const students=studentsQ.data?.data||[];const meta=studentsQ.data?.meta||{};
 const detailQ=useQuery({queryKey:['school-student-detail',selectedId],queryFn:()=>getStudentDetail(selectedId).then(r=>r.data.data),enabled:!!selectedId});
 const byLabel=useMemo(()=>Object.fromEntries(classes.map(c=>[`${c.class_name}-${c.section}`.toLowerCase(),c.id])),[classes]);

 const create=useMutation({mutationFn:()=>addStudent({...form,email:form.email||undefined,parentMobile:form.parentMobile||undefined,parentEmail:form.parentEmail||undefined,parentName:form.parentName||undefined}),onSuccess:async res=>{const x=res.data.data;toast.success(`Student created: ${x.student_code}`);if(x.temporaryPassword)toast(`Temporary password: ${x.temporaryPassword}`,{duration:15000,icon:'🔑'});setShowAdd(false);setForm(emptyStudent);await Promise.all([qc.invalidateQueries({queryKey:['school-students']}),qc.invalidateQueries({queryKey:['school-overview']})]);},onError:e=>toast.error(err(e))});
 const update=useMutation({mutationFn:()=>updateStudent(selectedId,edit),onSuccess:async()=>{toast.success('Student updated');setEdit(null);await Promise.all([qc.invalidateQueries({queryKey:['school-students']}),qc.invalidateQueries({queryKey:['school-student-detail',selectedId]})]);},onError:e=>toast.error(err(e))});
 const link=useMutation({mutationFn:()=>linkStudentParent(selectedId,parent),onSuccess:async res=>{toast.success(res.data.data.status==='LINKED'?'Parent linked':'Parent invitation saved');setParent({name:'',mobile:'',email:'',relation:'PARENT'});await qc.invalidateQueries({queryKey:['school-student-detail',selectedId]});},onError:e=>toast.error(err(e))});
 const bulk=useMutation({mutationFn:bulkAddStudents,onSuccess:async res=>{const created=res.data.data.created||[];setBulkMessage(`${created.length} Students imported successfully.`);await qc.invalidateQueries({queryKey:['school-students']});await qc.invalidateQueries({queryKey:['school-overview']});},onError:e=>toast.error(err(e))});

 async function importCsv(file){if(!file||!canAdmin)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)return toast.error('CSV has no data rows');const header=lines[0].split(',').map(x=>x.trim());const rows=[];for(const line of lines.slice(1)){const vals=line.split(',');const o=Object.fromEntries(header.map((h,i)=>[h,csvCell(vals[i])]));const key=`${o.class}-${o.section||'A'}`.toLowerCase();const id=byLabel[key];if(!id)return toast.error(`Class ${o.class}-${o.section||'A'} is not configured`);rows.push({name:o.name,mobile:o.mobile,email:o.email||undefined,classId:id,rollNumber:o.rollNumber||undefined,parentName:o.parentName||undefined,parentMobile:o.parentMobile||undefined,parentEmail:o.parentEmail||undefined,parentRelation:o.parentRelation||'PARENT'});}if(!rows.length)return toast.error('CSV has no Student rows');bulk.mutate(rows);}
 function template(){downloadText('vidyasetu-student-import.csv','name,mobile,email,class,section,rollNumber,parentName,parentMobile,parentEmail,parentRelation\nSample Student,9390000101,,8,A,8A25,Sample Parent,9490000101,,FATHER\n');}
 function openDetail(s){setSelectedId(s.id);setEdit(null);setParent({name:'',mobile:'',email:'',relation:'PARENT'});}
 const d=detailQ.data;

 return <div className="animate-fade-up">
  <SectionHeader title="👨‍🎓 Student Management" sub={`${meta.total||0} official Students`}>
   {canAdmin&&<><label className="btn-outline text-sm cursor-pointer">📥 Import CSV<input type="file" accept=".csv,text/csv" hidden onChange={e=>importCsv(e.target.files?.[0])}/></label><button className="btn-ghost text-sm" onClick={template}>Download Template</button><button className="btn-primary text-sm" onClick={()=>setShowAdd(v=>!v)}>+ Add Student</button></>}
  </SectionHeader>
  {!canAdmin&&<div className="card mb-5 text-sm" style={{borderLeft:'4px solid var(--saffron)',color:'var(--slate)'}}>Teacher access is read-only. Student admissions, transfers and Parent links are managed by the School Administrator.</div>}
  {bulkMessage&&<div className="card mb-4" style={{borderLeft:'4px solid var(--forest)',color:'var(--forest)'}}>{bulkMessage}</div>}

  {showAdd&&canAdmin&&<div className="card mb-5" style={{border:'2px solid var(--saffron)'}}><h3 className="font-display font-bold mb-4" style={{color:'var(--navy)'}}>Add Student to School</h3><div className="grid md:grid-cols-2 gap-3">
   <input className="input" placeholder="Full name *" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><input className="input" placeholder="10-digit mobile *" maxLength={10} value={form.mobile} onChange={e=>setForm(f=>({...f,mobile:e.target.value.replace(/\D/g,'')}))}/>
   <input className="input" type="email" placeholder="Email (optional)" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/><select className="input select" value={form.classId} onChange={e=>setForm(f=>({...f,classId:e.target.value}))}><option value="">Select class / section *</option>{classes.map(c=><option key={c.id} value={c.id}>Class {c.class_name}-{c.section}</option>)}</select>
   <input className="input" placeholder="Roll number" value={form.rollNumber} onChange={e=>setForm(f=>({...f,rollNumber:e.target.value}))}/><select className="input select" value={form.parentRelation} onChange={e=>setForm(f=>({...f,parentRelation:e.target.value}))}>{['FATHER','MOTHER','GUARDIAN','PARENT'].map(x=><option key={x}>{x}</option>)}</select>
   <input className="input" placeholder="Parent name (optional)" value={form.parentName} onChange={e=>setForm(f=>({...f,parentName:e.target.value}))}/><input className="input" placeholder="Parent mobile" maxLength={10} value={form.parentMobile} onChange={e=>setForm(f=>({...f,parentMobile:e.target.value.replace(/\D/g,'')}))}/>
  </div><p className="text-xs mt-3" style={{color:'var(--slate)'}}>A permanent Student ID, username and secure temporary password are generated automatically. Share the temporary credential privately with the Student.</p><div className="flex gap-2 mt-4"><button className="btn-primary" disabled={create.isPending||!form.name||form.mobile.length!==10||!form.classId} onClick={()=>create.mutate()}>{create.isPending?'Creating…':'Create Student'}</button><button className="btn-ghost" onClick={()=>setShowAdd(false)}>Cancel</button></div></div>}

  <div className="card mb-5"><div className="flex flex-wrap gap-3"><input className="input flex-1 min-w-[220px]" placeholder="🔍 Name / username / Student ID" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select className="input select w-auto" value={classId} onChange={e=>{setClassId(e.target.value);setPage(1)}}><option value="">All Classes</option>{classes.map(c=><option key={c.id} value={c.id}>Class {c.class_name}-{c.section}</option>)}</select></div></div>

  <div className="card">{studentsQ.isLoading?<TableSkeleton rows={8} cols={8}/>:studentsQ.isError?<div style={{color:'#C62828'}}>{err(studentsQ.error)}</div>:<div className="overflow-x-auto"><table className="tbl"><thead><tr><th>Student ID</th><th>Roll</th><th>Name</th><th>Class</th><th>Mobile</th><th>Attendance</th><th>Fee</th><th>Action</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td className="font-mono text-xs">{s.student_code}</td><td>{s.roll_number||'—'}</td><td><b>{s.name}</b><div className="text-xs" style={{color:'var(--slate)'}}>@{s.username}</div></td><td>Class {s.class_name}-{s.section}</td><td className="font-mono text-sm">{s.mobile}</td><td>{s.attendance_pct?`${Math.round(s.attendance_pct)}%`:'—'}</td><td><StatusBadge status={s.fee_status||'PENDING'}/></td><td><button className="text-xs font-bold px-3 py-1 rounded-lg" style={{background:'var(--saffron-pale)',color:'var(--saffron)'}} onClick={()=>openDetail(s)}>View</button></td></tr>)}</tbody></table>{!students.length&&<div className="py-10 text-center" style={{color:'var(--slate)'}}>No Students found.</div>}{meta.totalPages>1&&<div className="flex justify-between mt-4 pt-4" style={{borderTop:'1px solid var(--border)'}}><span className="text-xs">Page {meta.page} of {meta.totalPages}</span><div className="flex gap-2"><button className="btn-ghost text-xs" disabled={!meta.hasPrev} onClick={()=>setPage(p=>p-1)}>Prev</button><button className="btn-ghost text-xs" disabled={!meta.hasNext} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</div>}</div>

  {selectedId&&<div className="fixed inset-0 z-[1200] flex items-center justify-center p-4" style={{background:'rgba(13,27,62,.55)'}} onClick={e=>{if(e.target===e.currentTarget)setSelectedId(null)}}><div className="card w-full max-w-3xl max-h-[90vh] overflow-y-auto" style={{background:'white'}}>{detailQ.isLoading?<div className="py-10 text-center">Loading…</div>:detailQ.isError?<div style={{color:'#C62828'}}>{err(detailQ.error)}</div>:d&&<><div className="flex justify-between gap-3"><div><h2 className="font-display font-extrabold text-xl" style={{color:'var(--navy)'}}>{d.name}</h2><p className="text-xs" style={{color:'var(--slate)'}}>{d.student_code} · @{d.username}</p></div><button className="btn-ghost" onClick={()=>setSelectedId(null)}>✕</button></div>
   <div className="grid sm:grid-cols-4 gap-3 my-5">{[['Class',`${d.class_name||d.grade_level}-${d.section||''}`],['Roll',d.roll_number||'—'],['Attendance',d.attendance?.[0]?.percentage?`${Math.round(d.attendance[0].percentage)}%`:'—'],['Status',d.status]].map(([l,v])=><div className="p-3 rounded-xl" style={{background:'#F7F8FA'}} key={l}><div className="text-xs" style={{color:'var(--slate)'}}>{l}</div><div className="font-bold mt-1">{v}</div></div>)}</div>
   {canAdmin&&(!edit?<button className="btn-outline text-sm mb-5" onClick={()=>setEdit({name:d.name,email:d.email||'',mobile:d.mobile,classId:d.class_id||'',rollNumber:d.roll_number||'',status:d.status})}>Edit Student</button>:<div className="p-4 rounded-xl mb-5" style={{background:'#F7F8FA'}}><div className="grid sm:grid-cols-2 gap-2"><input className="input" value={edit.name} onChange={e=>setEdit(x=>({...x,name:e.target.value}))}/><input className="input" value={edit.mobile} onChange={e=>setEdit(x=>({...x,mobile:e.target.value.replace(/\D/g,'')}))}/><select className="input select" value={edit.classId} onChange={e=>setEdit(x=>({...x,classId:e.target.value}))}>{classes.map(c=><option key={c.id} value={c.id}>Class {c.class_name}-{c.section}</option>)}</select><input className="input" value={edit.rollNumber} onChange={e=>setEdit(x=>({...x,rollNumber:e.target.value}))}/><select className="input select" value={edit.status} onChange={e=>setEdit(x=>({...x,status:e.target.value}))}>{['ACTIVE','INACTIVE','TRANSFERRED','GRADUATED'].map(x=><option key={x}>{x}</option>)}</select></div><div className="flex gap-2 mt-3"><button className="btn-primary" disabled={update.isPending} onClick={()=>update.mutate()}>Save</button><button className="btn-ghost" onClick={()=>setEdit(null)}>Cancel</button></div></div>)}
   <h3 className="font-display font-bold mb-2" style={{color:'var(--navy)'}}>Parents / Guardians</h3><div className="space-y-2 mb-4">{(d.parents||[]).map(p=><div className="p-3 rounded-xl flex justify-between" style={{background:'var(--forest-pale)'}} key={p.id}><span><b>{p.name}</b> · {p.relation}</span><span className="text-sm">{p.mobile}</span></div>)}{!(d.parents||[]).length&&<p className="text-sm" style={{color:'var(--slate)'}}>No Parent account linked yet.</p>}</div>
   {canAdmin&&<><div className="grid sm:grid-cols-4 gap-2"><input className="input" placeholder="Parent name" value={parent.name} onChange={e=>setParent(x=>({...x,name:e.target.value}))}/><input className="input" placeholder="Mobile" maxLength={10} value={parent.mobile} onChange={e=>setParent(x=>({...x,mobile:e.target.value.replace(/\D/g,'')}))}/><input className="input" placeholder="Email" value={parent.email} onChange={e=>setParent(x=>({...x,email:e.target.value}))}/><select className="input select" value={parent.relation} onChange={e=>setParent(x=>({...x,relation:e.target.value}))}>{['FATHER','MOTHER','GUARDIAN','PARENT'].map(x=><option key={x}>{x}</option>)}</select></div><button className="btn-primary mt-2 text-sm" disabled={link.isPending||(!parent.mobile&&!parent.email)} onClick={()=>link.mutate()}>Link / Invite Parent</button></>}
  </>}</div></div>}
 </div>;
}
