#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_DIR="${PROJECT_DIR:-/var/www/vidyasetu}"
TARGET_BRANCH="${TARGET_BRANCH:-main}"
BACKUP_DIR="${BACKUP_DIR:-/root/vidyasetu-backups}"
NGINX_SITE="${NGINX_SITE:-/etc/nginx/sites-available/vidyasetu}"
BACKEND_ENV="$PROJECT_DIR/backend/.env"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
fail() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }
read_env_value() {
  local key="$1" file="$2"
  grep -m1 -E "^${key}=" "$file" 2>/dev/null | cut -d= -f2- || true
}

trap 'printf "\nERROR: deployment failed at line %s. PM2 was not intentionally changed before the build gate completed.\n" "$LINENO" >&2' ERR

[[ $EUID -eq 0 ]] || fail "Run this script as root."
[[ -d "$PROJECT_DIR/.git" ]] || fail "Repository not found at $PROJECT_DIR"
cd "$PROJECT_DIR"

log "1/8 Verify exact release checkout and native services"
[[ "$(git branch --show-current)" == "$TARGET_BRANCH" ]] || fail "Expected branch '$TARGET_BRANCH'."
[[ -z "$(git status --porcelain --untracked-files=no)" ]] || fail "Tracked working-tree changes exist."
for command_name in git node npm pm2 psql pg_dump redis-cli jq nginx curl; do
  command -v "$command_name" >/dev/null || fail "$command_name is not installed."
done

NODE_MAJOR="$(node -p "Number(process.versions.node.split('.')[0])")"
(( NODE_MAJOR >= 20 )) || fail "Node.js 20+ is required; found $(node --version)"

systemctl is-active --quiet postgresql || fail "Native PostgreSQL is not active."
systemctl is-active --quiet redis-server || fail "Native Redis is not active."
pg_isready -h 127.0.0.1 -p 5432 >/dev/null || fail "PostgreSQL is not accepting connections on 5432."
redis-cli -h 127.0.0.1 -p 6379 ping | grep -q PONG || fail "Redis is not responding on 6379."

# A deployment must run an already-reviewed main commit. It never deploys a feature branch.
git fetch origin "$TARGET_BRANCH"
LOCAL_SHA="$(git rev-parse HEAD)"
REMOTE_SHA="$(git rev-parse "origin/$TARGET_BRANCH")"
[[ "$LOCAL_SHA" == "$REMOTE_SHA" ]] || fail "Local $TARGET_BRANCH is not origin/$TARGET_BRANCH. Run: git pull --ff-only origin $TARGET_BRANCH"
printf 'Release commit: %s\n' "$LOCAL_SHA"

[[ -s "$BACKEND_ENV" ]] || fail "Missing $BACKEND_ENV. Production credentials are never generated by this deploy script."
DB_HOST="$(read_env_value DB_HOST "$BACKEND_ENV")"
DB_PORT="$(read_env_value DB_PORT "$BACKEND_ENV")"
DB_NAME="$(read_env_value DB_NAME "$BACKEND_ENV")"
DB_USER="$(read_env_value DB_USER "$BACKEND_ENV")"
DB_PASSWORD="$(read_env_value DB_PASSWORD "$BACKEND_ENV")"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-vidyasetu_db}"
DB_USER="${DB_USER:-postgres}"
[[ "$DB_HOST" == "127.0.0.1" || "$DB_HOST" == "localhost" ]] || fail "DB_HOST must target native PostgreSQL; found '$DB_HOST'."
[[ -n "$DB_PASSWORD" ]] || fail "DB_PASSWORD is missing from backend/.env"
export PGPASSWORD="$DB_PASSWORD"
psql -h 127.0.0.1 -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -Atc 'SELECT 1' >/dev/null \
  || fail "Native application database credentials do not authenticate."

log "2/8 Create mandatory pre-release PostgreSQL backup"
mkdir -p "$BACKUP_DIR"
SAFETY_DUMP="$BACKUP_DIR/vidyasetu_pre_release_$(date +%F_%H%M%S).dump"
pg_dump -h 127.0.0.1 -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -Fc > "$SAFETY_DUMP" \
  || fail "Could not create PostgreSQL safety dump."
test -s "$SAFETY_DUMP" || fail "PostgreSQL safety dump is empty."
printf 'Safety DB dump: %s\n' "$SAFETY_DUMP"

log "3/8 Read-only production schema and identity preflight"
for table_name in \
  users students schools school_classes teachers teacher_assignments subjects \
  attendance fee_structures fee_invoices fee_payments timetable_periods exams \
  exam_attempts announcements notifications parent_student_links platform_config \
  subscription_events support_tickets audit_log; do
  exists="$(psql -h 127.0.0.1 -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT to_regclass('public.$table_name') IS NOT NULL;")"
  [[ "$exists" == "t" ]] || fail "Required table '$table_name' is missing. No migration was attempted. Backup: $SAFETY_DUMP"
done

TEACHER_ENUM="$(psql -h 127.0.0.1 -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT COUNT(*) FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='user_role' AND e.enumlabel='TEACHER';")"
[[ "$TEACHER_ENUM" == "1" ]] || fail "TEACHER role is missing. No migration was attempted."
NULL_USERNAMES="$(psql -h 127.0.0.1 -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT COUNT(*) FROM users WHERE username IS NULL OR BTRIM(username)='';")"
[[ "$NULL_USERNAMES" == "0" ]] || fail "Users without usernames remain."
NULL_CODES="$(psql -h 127.0.0.1 -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT COUNT(*) FROM students WHERE student_code IS NULL OR BTRIM(student_code)='';")"
[[ "$NULL_CODES" == "0" ]] || fail "Students without Student IDs remain."

printf 'No production migration or seed SQL will be executed by this release.\n'

log "4/8 Run the exact production-equivalent TypeScript build gate"
PROJECT_DIR="$PROJECT_DIR" bash "$PROJECT_DIR/scripts/build-production-native.sh"

log "5/8 Reload native PM2 applications from version-controlled runtime config"
cd "$PROJECT_DIR"
pm2 startOrReload ecosystem.config.cjs --update-env
pm2 save

for i in {1..40}; do
  if curl -fsS http://127.0.0.1:5000/health >/dev/null; then break; fi
  sleep 1
  [[ "$i" -lt 40 ]] || { pm2 logs vs-api --lines 120 --nostream; fail "Compiled API did not become healthy."; }
done

for i in {1..40}; do
  code="$(curl -sS -o /dev/null -w '%{http_code}' http://127.0.0.1:3000/ || true)"
  [[ "$code" =~ ^(200|301|302|307|308)$ ]] && break
  sleep 1
  [[ "$i" -lt 40 ]] || { pm2 logs vs-web --lines 120 --nostream; fail "Next.js did not become healthy."; }
done

API_SCRIPT="$(pm2 jlist | jq -r '.[] | select(.name=="vs-api") | .pm2_env.pm_exec_path' | head -1)"
[[ "$API_SCRIPT" == "$PROJECT_DIR/backend/dist/index.js" ]] || fail "vs-api is not running compiled dist/index.js; found '$API_SCRIPT'"

log "6/8 Run local non-destructive role smoke checks"
cd "$PROJECT_DIR"
API_BASE=http://127.0.0.1:5000/api/v1 WEB_BASE=http://127.0.0.1:3000 bash scripts/student-production-smoke.sh
API_BASE=http://127.0.0.1:5000/api/v1 WEB_BASE=http://127.0.0.1:3000 bash scripts/school-production-smoke.sh
API_BASE=http://127.0.0.1:5000/api/v1 WEB_BASE=http://127.0.0.1:3000 bash scripts/parent-admin-production-smoke.sh

log "7/8 Validate existing Nginx and public routes without rewriting configuration"
[[ -f "$NGINX_SITE" ]] || fail "Nginx site file not found: $NGINX_SITE"
nginx -t
WEB_BASE=https://vidyasetu.sbs API_BASE=https://vidyasetu.sbs/api/v1 bash scripts/student-production-smoke.sh
WEB_BASE=https://vidyasetu.sbs API_BASE=https://vidyasetu.sbs/api/v1 bash scripts/school-production-smoke.sh
WEB_BASE=https://vidyasetu.sbs API_BASE=https://vidyasetu.sbs/api/v1 bash scripts/parent-admin-production-smoke.sh

log "8/8 Report release state"
pm2 status
printf '\nNative release deployment completed.\nCommit: %s\nBackup: %s\n' "$LOCAL_SHA" "$SAFETY_DUMP"
printf 'API runtime: %s\n' "$API_SCRIPT"
printf 'No Docker command, database migration, seed, or Nginx rewrite was executed.\n'
