'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import toast from 'react-hot-toast';
import {getSyllabusOptions,getSyllabusDetail,importSyllabus,changeSyllabusStatus,linkSyllabusResource,retireSyllabusTopic,type SyllabusRow} from '@/services/syllabusService';
const blank:SyllabusRow={gradeCode:'CLASS_6',subjectId:'',chapter:'',topic:'',topicHi:'',learningOutcome:'',evidenceUrl:'',pageReference:''};
const message=(e:unknown)=>{const error=e as {response?:{data?:{error?:{message?:string}}}};return error.response?.data?.error?.message||'Syllabus action failed. Check required fields and server migration 053.';};
export default function AdminSyllabus(){
 const client=useQueryClient();const date=new Date();const start=date.getMonth()<3?date.getFullYear()-1:date.getFullYear();
 const [board,setBoard]=useState('');const [year,setYear]=useState(`${start}-${String(start+1).slice(-2)}`);const [title,setTitle]=useState('');const [source,setSource]=useState('');const [row,setRow]=useState<SyllabusRow>({...blank});const [rows,setRows]=useState<SyllabusRow[]>([]);const [bulk,setBulk]=useState('');const [selected,setSelected]=useState('');const [note,setNote]=useState('');const [confirmed,setConfirmed]=useState(false);const [resourceId,setResourceId]=useState('');const [topicId,setTopicId]=useState('');
 const options=useQuery({queryKey:['syllabus-options'],queryFn:()=>getSyllabusOptions().then(r=>r.data.data)});
 const detail=useQuery({queryKey:['syllabus-detail',selected],queryFn:()=>getSyllabusDetail(selected).then(r=>r.data.data),enabled:Boolean(selected)});
 const refresh=()=>{client.invalidateQueries({queryKey:['syllabus-options']});client.invalidateQueries({queryKey:['syllabus-detail']});client.invalidateQueries({queryKey:['content-factory-options']});client.invalidateQueries({queryKey:['learning-pipeline-options']});};
 const save=useMutation({mutationFn:()=>importSyllabus({boardCode:board,academicYear:year,title,sourceUrl:source,rows}),onSuccess:r=>{setSelected(r.data.data?.id||'');setRows([]);refresh();toast.success('Syllabus saved as draft. Review before approval.');},onError:e=>toast.error(message(e))});
 const status=useMutation({mutationFn:(value:string)=>changeSyllabusStatus(selected,value,note),onSuccess:()=>{refresh();setConfirmed(false);toast.success('Syllabus status updated');},onError:e=>toast.error(message(e))});
 const link=useMutation({mutationFn:()=>linkSyllabusResource(topicId,resourceId),onSuccess:()=>{refresh();toast.success('Draft mapped. Complete Library review before publication.');},onError:e=>toast.error(message(e))});
 const retire=useMutation({mutationFn:({id,retired}:{id:string;retired:boolean})=>retireSyllabusTopic(id,retired,note),onSuccess:()=>{refresh();toast.success('Topic visibility updated. Learner history retained.');},onError:e=>toast.error(message(e))});
 const field=(key:keyof SyllabusRow,value:string)=>setRow(old=>({...old,[key]:value}));
 return <div style={{padding:24,color:'#14213D',background:'#F3F6FB'}}><h1>Verified syllabus workspace</h1><p>Maintain board/year-specific topics and learning outcomes. This controls the student syllabus and content search; it does not publish learning content or establish media rights.</p>
 {options.isError&&<p role="alert">Syllabus options could not load. Verify admin access and migration 053. <button className="btn-secondary" onClick={()=>options.refetch()}>Retry</button></p>}
 <section className="admin-panel" style={{padding:20,marginTop:20}}><h2>Prepare syllabus topic rows</h2><p>Use official syllabus and textbook evidence. Enter the scope in the title, such as “Class 6 Mathematics · reviewed chapter list”. Do not imply complete K–12 coverage from a partial import.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}><label>Board<select className="admin-select" value={board} onChange={e=>setBoard(e.target.value)}><option value="">Select board</option>{options.data?.boards.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label>Academic year<input className="admin-input" value={year} onChange={e=>setYear(e.target.value)}/></label><label>Syllabus title / scope<input className="admin-input" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Official source URL<input className="admin-input" type="url" value={source} onChange={e=>setSource(e.target.value)}/></label></div>
 <form onSubmit={e=>{e.preventDefault();setRows(old=>[...old,{...row}]);setRow({...row,topic:'',topicHi:'',learningOutcome:'',pageReference:''});}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:16}}><label>Class<select className="admin-select" value={row.gradeCode} onChange={e=>field('gradeCode',e.target.value)}>{options.data?.grades.map(g=><option key={g.code} value={g.code}>{g.name}</option>)}</select></label><label>Subject<select required className="admin-select" value={row.subjectId} onChange={e=>field('subjectId',e.target.value)}><option value="">Select subject</option>{options.data?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{(['chapter','topic','topicHi','learningOutcome','evidenceUrl','pageReference'] as const).map(key=><label key={key}>{({chapter:'Chapter / developmental domain',topic:'Topic',topicHi:'Hindi topic (optional)',learningOutcome:'Learning outcome',evidenceUrl:'Exact evidence URL',pageReference:'Page / section reference'})[key]}<input className="admin-input" required={key!=='topicHi'} type={key==='evidenceUrl'?'url':'text'} value={row[key]||''} onChange={e=>field(key,e.target.value)}/></label>)}</div><button className="btn-primary" style={{marginTop:12}}>Add topic row</button></form>
 <p>{rows.length} prepared rows · Saving adds or updates matching topic names; it does not delete omitted topics.</p><ul>{rows.map((r,i)=><li key={i}>{r.gradeCode} · {r.chapter} → {r.topic} <button className="btn-secondary" onClick={()=>setRows(old=>old.filter((_,j)=>j!==i))}>Remove prepared row</button></li>)}</ul>
 <details><summary>Advanced bulk JSON import</summary><p>Paste an array of the same topic rows. Subject IDs come from the subject selector; maximum 500 rows. Extraction from PDFs is not automatic.</p><textarea aria-label="Bulk syllabus rows" className="admin-textarea" value={bulk} onChange={e=>setBulk(e.target.value)}/><button className="btn-secondary" onClick={()=>{try{const parsed=JSON.parse(bulk);if(!Array.isArray(parsed)||!parsed.length||parsed.length>500)throw Error();if(parsed.some(r=>!r||typeof r!=='object'||typeof r.topic!=='string'||typeof r.chapter!=='string'))throw Error();setRows(parsed);toast.success('Rows prepared; server validation runs when saving');}catch{toast.error('Enter a valid array of 1–500 topic rows');}}}>Prepare bulk rows</button><button className="btn-secondary" onClick={()=>setBulk(JSON.stringify([{...row}],null,2))}>Use current row as template</button></details>
 <button className="btn-primary" disabled={save.isPending||!rows.length||!board||!title||!source} onClick={()=>save.mutate()}>Save draft syllabus</button></section>
 <section className="admin-panel" style={{padding:20,marginTop:20}}><h2>Review and manage versions</h2><select className="admin-select" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false);}}><option value="">Select a syllabus version</option>{options.data?.versions.map(v=><option key={v.id} value={v.id}>{v.board_code} · {v.academic_year} · {v.status} · {v.verified_at?'reviewed':'unverified'}</option>)}</select>
 {detail.isError&&<p role="alert">Could not load syllabus. <button className="btn-secondary" onClick={()=>detail.refetch()}>Retry</button></p>}{detail.data&&<><h3>{detail.data.version.title}</h3><a href={detail.data.version.source_url} target="_blank" rel="noopener noreferrer">Inspect source evidence ↗</a><p>{detail.data.topics.length} topic records. Active means students can see this approved version; content still needs separate review.</p><label>Review / correction note<textarea className="admin-textarea" value={note} onChange={e=>setNote(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I checked the topic list, outcomes, applicable year and page evidence against official sources for the stated scope.</label><div style={{display:'flex',flexWrap:'wrap',gap:12,marginTop:12}}><button className="btn-secondary" disabled={status.isPending||!confirmed||note.trim().length<10} onClick={()=>status.mutate('ACTIVE')}>Approve & make student-visible</button><button className="btn-secondary" disabled={status.isPending||note.trim().length<10} onClick={()=>status.mutate('DRAFT')}>Return to draft for correction</button><button className="btn-secondary" disabled={status.isPending||note.trim().length<10} onClick={()=>status.mutate('ARCHIVED')}>Archive version</button></div><p>Draft/archived versions are hidden from students. Existing lesson and assessment progress is retained. New years do not automatically inherit mastery.</p>
 {detail.data.topics.map(t=><article key={t.id} style={{borderTop:'1px solid #DCE3EE',padding:'14px 0'}}><strong>{t.grade_code} · {t.subject} · {t.chapter} → {t.title}</strong><p>{t.learning_outcome}</p>{t.is_retired&&<strong>Retired topic · historical progress retained</strong>}{detail.data?.version.status==='DRAFT'&&<button className="btn-secondary" onClick={()=>{const version=detail.data!.version;setBoard(version.board_code||'');setYear(version.academic_year);setTitle(version.title);setSource(version.source_url);setRow({gradeCode:t.grade_code,subjectId:t.subject_id,chapter:t.chapter,topic:t.title,topicHi:t.title_hi||'',learningOutcome:t.learning_outcome||'',evidenceUrl:t.evidence_url||'',pageReference:t.page_reference||''});window.scrollTo({top:0,behavior:'smooth'});}}>Edit topic row</button>}{detail.data?.version.status==='DRAFT'&&<button className="btn-secondary" disabled={retire.isPending||note.trim().length<10} onClick={()=>retire.mutate({id:t.id,retired:!t.is_retired})}>{t.is_retired?'Restore for review':'Remove topic from active syllabus'}</button>}<p>Published resources: {t.coverage?.published_count||0} · Formats: {t.coverage?.formats.join(", ")||"missing"} · Difficulty: {t.coverage?.difficulties.filter(Boolean).join(", ")||"missing"}</p><a href={t.evidence_url} target="_blank" rel="noopener noreferrer">Evidence: {t.page_reference}</a>{!t.is_retired&&detail.data?.version.status==='ACTIVE'&&detail.data.version.verified_at&&<p><Link href={`/admin/learning/factory?${new URLSearchParams({grade:t.grade_code,board:detail.data.version.board_code||'',subject:t.subject_id,chapter:t.chapter,topic:t.title,concept:t.concept_id||'',year:detail.data.version.academic_year})}`}>Find content for this topic →</Link></p>}</article>)}<h3>Map an existing Library draft</h3><p>Choose an academic draft from Library. Subject and grade must match. Published content must return to draft before changing its curriculum mapping.</p><select className="admin-select" value={topicId} onChange={e=>setTopicId(e.target.value)}><option value="">Select topic</option>{detail.data.topics.map(t=><option key={t.id} value={t.id}>{t.grade_code} · {t.chapter} · {t.title}</option>)}</select><select className="admin-select" aria-label="Library draft resource" value={resourceId} onChange={e=>setResourceId(e.target.value)}><option value="">Choose Library draft</option>{options.data?.drafts.filter(r=>{const topic=detail.data?.topics.find(t=>t.id===topicId);return topic&&r.subject_id===topic.subject_id&&r.grade_codes?.includes(topic.grade_code);}).map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select><button className="btn-secondary" disabled={link.isPending||!topicId||!resourceId} onClick={()=>link.mutate()}>Map Library draft</button><h3>Change history</h3><ul>{detail.data.history.map((h,i)=><li key={i}>{new Date(h.created_at).toLocaleString()} · {h.operation}</li>)}</ul></>}
 </section></div>;
}
