'use client';

import { useEffect,useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import useAuthStore from '@/store/authStore';
import useLanguageStore from '@/store/languageStore';
import { getTeachers } from '@/services/schoolService';
import {
  createSchoolPtmSession,createSchoolPtmSlot,getSchoolPtmBookings,getSchoolPtmSessions,getSchoolPtmSlots,
  updatePtmOutcome,updateSchoolPtmSessionStatus,type PtmSession,type PtmSessionStatus,
} from '@/services/ptmService';
import { apiErrorText } from '@/utils/errors';

const toIso=(value:string)=>new Date(value).toISOString();
const local=(value?:string)=>value?new Date(value).toLocaleString('en-IN'):'—';

export default function SchoolPtmPage(){
  const {user}=useAuthStore(); const {t}=useLanguageStore();
  const isTeacher=user?.role==='TEACHER'; const qc=useQueryClient();
  const sessionsQ=useQuery({queryKey:['school-ptm-sessions'],queryFn:()=>getSchoolPtmSessions().then(r=>r.data.data||[])});
  const teachersQ=useQuery({queryKey:['school-teachers'],queryFn:()=>getTeachers().then(r=>r.data.data||[]),enabled:!isTeacher});
  const [sessionId,setSessionId]=useState('');
  useEffect(()=>{if(!sessionId&&sessionsQ.data?.[0]?.id)setSessionId(sessionsQ.data[0].id);},[sessionsQ.data,sessionId]);
  const slotsQ=useQuery({queryKey:['school-ptm-slots',sessionId],queryFn:()=>getSchoolPtmSlots(sessionId||undefined).then(r=>r.data.data||[]),enabled:Boolean(sessionId)});
  const bookingsQ=useQuery({queryKey:['school-ptm-bookings',sessionId],queryFn:()=>getSchoolPtmBookings(sessionId||undefined).then(r=>r.data.data||[]),enabled:Boolean(sessionId)});
  const selected=useMemo(()=>sessionsQ.data?.find(s=>s.id===sessionId),[sessionsQ.data,sessionId]);
  const [sessionForm,setSessionForm]=useState({title:'',description:'',startsAt:'',endsAt:'',bookingOpensAt:'',bookingClosesAt:''});
  const [slotForm,setSlotForm]=useState({teacherId:'',startsAt:'',endsAt:'',location:''});
  const [outcomes,setOutcomes]=useState<Record<string,{outcomeNote:string;agreedAction:string;followUpAt:string}>>({});
  useEffect(()=>{if(!slotForm.teacherId&&teachersQ.data?.[0]?.id)setSlotForm(v=>({...v,teacherId:teachersQ.data?.[0]?.id||''}));},[teachersQ.data,slotForm.teacherId]);
  const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['school-ptm-sessions']}),qc.invalidateQueries({queryKey:['school-ptm-slots']}),qc.invalidateQueries({queryKey:['school-ptm-bookings']}),qc.invalidateQueries({queryKey:['teacher-academic-workspace']})]);};
  const createSessionM=useMutation({mutationFn:()=>createSchoolPtmSession({title:sessionForm.title,description:sessionForm.description||undefined,startsAt:toIso(sessionForm.startsAt),endsAt:toIso(sessionForm.endsAt),bookingOpensAt:toIso(sessionForm.bookingOpensAt),bookingClosesAt:toIso(sessionForm.bookingClosesAt)}),onSuccess:async(r)=>{toast.success('PTM draft created');setSessionForm({title:'',description:'',startsAt:'',endsAt:'',bookingOpensAt:'',bookingClosesAt:''});setSessionId(r.data.data.id);await refresh();},onError:(e:unknown)=>toast.error(apiErrorText(e,'Could not create PTM'))});
  const statusM=useMutation({mutationFn:({id,status}:{id:string;status:Exclude<PtmSessionStatus,'DRAFT'>})=>updateSchoolPtmSessionStatus(id,status),onSuccess:refresh,onError:(e:unknown)=>toast.error(apiErrorText(e,'Could not update PTM'))});
  const createSlotM=useMutation({mutationFn:()=>createSchoolPtmSlot(sessionId,{teacherId:slotForm.teacherId,startsAt:toIso(slotForm.startsAt),endsAt:toIso(slotForm.endsAt),location:slotForm.location||undefined}),onSuccess:async()=>{toast.success('Teacher slot added');setSlotForm(v=>({...v,startsAt:'',endsAt:'',location:''}));await refresh();},onError:(e:unknown)=>toast.error(apiErrorText(e,'Could not add slot'))});
  const outcomeM=useMutation({mutationFn:({id,status}:{id:string;status:'COMPLETED'|'NO_SHOW'})=>{const f=outcomes[id]||{outcomeNote:'',agreedAction:'',followUpAt:''};return updatePtmOutcome(id,{status,outcomeNote:f.outcomeNote||undefined,agreedAction:f.agreedAction||undefined,followUpAt:f.followUpAt?toIso(f.followUpAt):null});},onSuccess:async()=>{toast.success('PTM outcome recorded');await refresh();},onError:(e:unknown)=>toast.error(apiErrorText(e,'Could not record outcome'))});
  const error=sessionsQ.error||slotsQ.error||bookingsQ.error;
  const nextStatus=(s:PtmSession):Exclude<PtmSessionStatus,'DRAFT'>|null=>s.status==='DRAFT'?'OPEN':s.status==='OPEN'?'CLOSED':s.status==='CLOSED'?'COMPLETED':null;

  return <div className="animate-fade-up space-y-5">
    <div><h1 className="font-display font-extrabold text-2xl" style={{color:'var(--navy)'}}>🤝 {t('PTM और लर्निंग फॉलो-अप','PTM & Learning Follow-up')}</h1><p className="text-sm mt-1" style={{color:'var(--slate)'}}>{isTeacher?t('अपने PTM स्लॉट, हस्तक्षेप संदर्भ और सहमत फॉलो-अप एक जगह देखें।','See your PTM slots, intervention context and agreed follow-up in one place.'):t('नियंत्रित PTM विंडो बनाएं और लर्निंग हस्तक्षेप को परिवार फॉलो-अप से जोड़ें।','Create governed PTM windows and connect learning interventions to family follow-up.')}</p></div>
    {error&&<div className="card" style={{color:'#B42318'}}>{apiErrorText(error)}</div>}

    {!isTeacher&&<div className="card"><h2 className="font-bold text-lg mb-3">{t('PTM सत्र बनाएं','Create PTM session')}</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3"><input className="input" placeholder="PTM title" value={sessionForm.title} onChange={e=>setSessionForm({...sessionForm,title:e.target.value})}/><input className="input" placeholder="Description" value={sessionForm.description} onChange={e=>setSessionForm({...sessionForm,description:e.target.value})}/><label className="text-xs">PTM starts<input className="input mt-1" type="datetime-local" value={sessionForm.startsAt} onChange={e=>setSessionForm({...sessionForm,startsAt:e.target.value})}/></label><label className="text-xs">PTM ends<input className="input mt-1" type="datetime-local" value={sessionForm.endsAt} onChange={e=>setSessionForm({...sessionForm,endsAt:e.target.value})}/></label><label className="text-xs">Booking opens<input className="input mt-1" type="datetime-local" value={sessionForm.bookingOpensAt} onChange={e=>setSessionForm({...sessionForm,bookingOpensAt:e.target.value})}/></label><label className="text-xs">Booking closes<input className="input mt-1" type="datetime-local" value={sessionForm.bookingClosesAt} onChange={e=>setSessionForm({...sessionForm,bookingClosesAt:e.target.value})}/></label></div><button className="btn btn-primary mt-3" disabled={createSessionM.isPending||!sessionForm.title||!sessionForm.startsAt||!sessionForm.endsAt||!sessionForm.bookingOpensAt||!sessionForm.bookingClosesAt} onClick={()=>createSessionM.mutate()}>{t('ड्राफ्ट PTM बनाएं','Create draft PTM')}</button></div>}

    <div className="card"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold text-lg">{t('PTM सत्र','PTM sessions')}</h2><select className="input select w-auto min-w-[260px]" value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">Select session</option>{(sessionsQ.data||[]).map(s=><option key={s.id} value={s.id}>{s.title} · {s.status}</option>)}</select></div>{selected&&<div className="mt-4 p-4 rounded-xl" style={{background:'#F8FBF9',border:'1px solid var(--border)'}}><div className="flex flex-wrap justify-between gap-3"><div><div className="font-bold">{selected.title}</div><div className="text-sm mt-1">{local(selected.starts_at)} – {local(selected.ends_at)}</div><div className="text-xs mt-1" style={{color:'var(--slate)'}}>Booking: {local(selected.booking_opens_at)} → {local(selected.booking_closes_at)} · {selected.slot_count||0} slots · {selected.booked_count||0} booked</div></div><div className="flex gap-2 items-start"><span className="status-badge">{selected.status}</span>{!isTeacher&&nextStatus(selected)&&<button className="btn btn-outline text-sm" onClick={()=>statusM.mutate({id:selected.id,status:nextStatus(selected)!})}>{nextStatus(selected)}</button>}{!isTeacher&&!['COMPLETED','CANCELLED'].includes(selected.status)&&<button className="btn btn-outline text-sm" onClick={()=>statusM.mutate({id:selected.id,status:'CANCELLED'})}>Cancel PTM</button>}</div></div></div>}</div>

    {!isTeacher&&selected&&<div className="card"><h2 className="font-bold text-lg mb-3">{t('शिक्षक स्लॉट जोड़ें','Add Teacher slot')}</h2><div className="grid md:grid-cols-4 gap-3"><select className="input select" value={slotForm.teacherId} onChange={e=>setSlotForm({...slotForm,teacherId:e.target.value})}><option value="">Teacher</option>{(teachersQ.data||[]).filter(x=>x.status==='ACTIVE').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="input" type="datetime-local" value={slotForm.startsAt} onChange={e=>setSlotForm({...slotForm,startsAt:e.target.value})}/><input className="input" type="datetime-local" value={slotForm.endsAt} onChange={e=>setSlotForm({...slotForm,endsAt:e.target.value})}/><input className="input" placeholder="Room / location" value={slotForm.location} onChange={e=>setSlotForm({...slotForm,location:e.target.value})}/></div><button className="btn btn-primary mt-3" disabled={createSlotM.isPending||!slotForm.teacherId||!slotForm.startsAt||!slotForm.endsAt} onClick={()=>createSlotM.mutate()}>{t('स्लॉट जोड़ें','Add slot')}</button></div>}

    <div className="card"><h2 className="font-bold text-lg mb-3">{t('बैठकें और कार्रवाई','Appointments & actions')}</h2><div className="space-y-3">{(bookingsQ.data||[]).map(b=>{const form=outcomes[b.id]||{outcomeNote:'',agreedAction:'',followUpAt:''};return <div key={b.id} className="p-4 rounded-xl" style={{border:'1px solid var(--border)',background:b.intervention_id?'#FFF8EE':'#fff'}}><div className="flex flex-wrap justify-between gap-3"><div><b>{b.student_name}</b><div className="text-xs mt-1" style={{color:'var(--slate)'}}>{b.teacher_name} · {local(b.starts_at)} · {b.location||'School campus'}</div>{b.intervention_title&&<div className="text-xs font-bold mt-2" style={{color:'#9A6500'}}>🎯 {b.intervention_title} · {b.intervention_status}</div>}</div><span className="status-badge">{b.status}</span></div>{b.status==='BOOKED'?<div className="grid md:grid-cols-3 gap-3 mt-4"><textarea className="input min-h-20" placeholder="Meeting outcome" value={form.outcomeNote} onChange={e=>setOutcomes(v=>({...v,[b.id]:{...form,outcomeNote:e.target.value}}))}/><textarea className="input min-h-20" placeholder="Agreed learning action" value={form.agreedAction} onChange={e=>setOutcomes(v=>({...v,[b.id]:{...form,agreedAction:e.target.value}}))}/><div><label className="text-xs font-bold">Follow-up date</label><input className="input mt-1" type="datetime-local" value={form.followUpAt} onChange={e=>setOutcomes(v=>({...v,[b.id]:{...form,followUpAt:e.target.value}}))}/><div className="flex gap-2 mt-3"><button className="btn btn-primary text-xs" onClick={()=>outcomeM.mutate({id:b.id,status:'COMPLETED'})}>Complete</button><button className="btn btn-outline text-xs" onClick={()=>outcomeM.mutate({id:b.id,status:'NO_SHOW'})}>No show</button></div></div></div>:<div className="grid md:grid-cols-3 gap-3 mt-3 text-sm"><div><b>Outcome</b><p>{b.outcome_note||'—'}</p></div><div><b>Agreed action</b><p>{b.agreed_action||'—'}</p></div><div><b>Follow-up</b><p>{local(b.follow_up_at||undefined)}</p></div></div>}</div>;})}{!bookingsQ.isLoading&&!(bookingsQ.data||[]).length&&<div className="py-8 text-center text-sm" style={{color:'var(--slate)'}}>{t('कोई बैठक बुक नहीं है।','No appointments booked.')}</div>}</div></div>
  </div>;
}
