'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useQuery,useQueryClient,useMutation} from '@tanstack/react-query';
import toast from 'react-hot-toast';
import {getMySyllabus,saveSyllabusProfile,getSyllabusDocuments,getSyllabusDocument} from '@/services/syllabusService';
export default function MySyllabus(){
 const client=useQueryClient();const [board,setBoard]=useState('');const [grade,setGrade]=useState('');const [year,setYear]=useState('');const [language,setLanguage]=useState('en');
 const [browseBoard,setBrowseBoard]=useState('');const [browseGrade,setBrowseGrade]=useState('');const [browseSubject,setBrowseSubject]=useState('');const [search,setSearch]=useState('');const [docId,setDocId]=useState('');
 const q=useQuery({queryKey:['my-syllabus'],queryFn:()=>getMySyllabus().then(r=>r.data.data)});const data=q.data;
 const docs=useQuery({queryKey:['student-syllabus-documents',browseBoard,browseGrade,browseSubject,search],queryFn:()=>getSyllabusDocuments({boardCode:browseBoard,gradeCode:browseGrade,subjectId:browseSubject,query:search},false).then(r=>r.data.data)});
 const doc=useQuery({queryKey:['student-syllabus-document',docId],queryFn:()=>getSyllabusDocument(docId,false).then(r=>r.data.data),enabled:Boolean(docId)});
 useEffect(()=>{if(data){setBoard(data.profile.boardCode||'');setGrade(data.profile.gradeCode);setYear(data.profile.academicYear);setLanguage(data.profile.language);}},[data]);
 const save=useMutation({mutationFn:()=>saveSyllabusProfile({boardCode:board,gradeCode:grade,academicYear:year,language}),onSuccess:()=>{client.invalidateQueries({queryKey:['my-syllabus']});client.invalidateQueries({queryKey:['canonical-learning-catalogue']});toast.success('Learning profile saved');},onError:()=>toast.error('Could not save. School-linked board/class assignments cannot be changed here.')});
 if(q.isLoading)return <p role="status">Loading syllabus…</p>;
 if(q.isError)return <div className="card p-6"><h1>My Syllabus</h1><p role="alert">Syllabus could not be loaded. Sign in with an active student profile; the server must have migration 053.</p><button onClick={()=>q.refetch()}>Retry</button></div>;
 if(!data)return null;
 const s=data.summary;
 return <div className="space-y-5"><div className="card p-5"><Link href="/subjects">← Learning subjects</Link><h1 className="text-2xl font-bold mt-3">{language==='hi'?'मेरा पाठ्यक्रम':'My Syllabus'}</h1><p>Approved topics for your board, class and academic year. Lesson completion and assessed mastery are separate.</p>
 <form className="flex flex-wrap gap-3 mt-4" onSubmit={e=>{e.preventDefault();save.mutate();}}><label style={{flex:'1 1 180px',minWidth:0}}>Board<select className="input" required disabled={data.profile.schoolLinked} value={board} onChange={e=>setBoard(e.target.value)}><option value="">Select board</option>{data.options.boards.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label style={{flex:'1 1 140px',minWidth:0}}>Class<select className="input" required disabled={data.profile.schoolLinked} value={grade} onChange={e=>setGrade(e.target.value)}>{data.options.grades.map(g=><option key={g.code} value={g.code}>{g.name}</option>)}</select></label><label style={{flex:'1 1 150px',minWidth:0}}>Academic year<input className="input" required pattern="20[0-9]{2}-[0-9]{2}" value={year} onChange={e=>setYear(e.target.value)} list="syllabus-years"/><datalist id="syllabus-years">{data.options.years.map(y=><option key={y}>{y}</option>)}</datalist></label><label style={{flex:'1 1 140px',minWidth:0}}>Language<select className="input" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="hi">हिन्दी</option></select></label><button className="btn-primary" disabled={save.isPending}>Save learning profile</button></form>{data.profile.schoolLinked&&<p className="text-sm mt-2">Your school assigns your board and class. Ask the school administrator to correct them.</p>}</div>
 {!data.version||!data.topics.length?<div className="card p-5"><h2>Syllabus awaiting verification</h2><p>No approved topics are available for this board, class and year yet. This does not mean the syllabus is empty or complete.</p></div>:<><div className="card p-5"><h2 className="font-bold">{data.version.title}</h2><a href={data.version.source_url} target="_blank" rel="noopener noreferrer">Official syllabus evidence ↗</a><div className="flex flex-wrap gap-5 mt-3"><span>{s?.totalTopics} approved topics</span><span>{s?.coveredTopics} topics with published material</span><span>{s?.completedTopics} topics with all available unlocked lessons completed</span><span>{s?.masteredTopics} assessed as mastered</span></div><p className="text-sm">Unavailable and locked topics remain in the syllabus. Completion describes available lessons; it is not certification of understanding.</p></div>
 {[...new Set(data.topics.map(t=>`${t.subject} · ${t.chapter}`))].map(group=><section key={group} className="card p-5"><h2 className="font-bold text-lg">{group}</h2>{data.topics.filter(t=>`${t.subject} · ${t.chapter}`===group).map(t=><article key={t.id} className="border-t py-4 mt-3"><h3 className="font-semibold">{language==='hi'&&t.title_hi?t.title_hi:t.title}</h3><p>{t.learning_outcome}</p><Link className="underline text-sm" href={`/learn/library?${new URLSearchParams({q:t.title,board:data.profile.boardCode||'',grade:t.grade_code})}`}>Find learning content for this syllabus topic →</Link><p className="text-sm my-2">Lessons: {t.completedResources}/{t.availableResources} · Mastery: {t.mastered?'Demonstrated':t.masteryPct!=null?`${t.masteryPct}% assessment evidence`:'Assessment pending'}</p>{!t.resources?.length?<p>Content coming soon</p>:<ul className="space-y-2">{t.resources.map(r=><li key={r.id}>{r.locked?<span>🔒 {r.title} · Subscription required</span>:<Link className="underline" href={`/subjects/resource/${r.id}`}>{language==='hi'&&r.title_hi?r.title_hi:r.title} · {r.resource_type} {r.difficulty||''} {r.completed?'✓':''}</Link>}</li>)}</ul>}</article>)}</section>)}</>}
 <section className="card p-5"><h2 className="text-xl font-bold">Syllabus documents and topic search</h2><p>Search approved source documents by board, class and subject, or leave filters blank for a wider search. Use the content library link to find available lessons for any topic, whether it is in a syllabus or entered as a free-text search.</p><div className="flex flex-wrap gap-3 mt-4"><label style={{flex:'1 1 180px'}}>Board<select className="input" value={browseBoard} onChange={e=>setBrowseBoard(e.target.value)}><option value="">All boards</option>{data.options.boards.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label style={{flex:'1 1 140px'}}>Class<select className="input" value={browseGrade} onChange={e=>setBrowseGrade(e.target.value)}><option value="">All classes</option>{data.options.grades.map(g=><option key={g.code} value={g.code}>{g.name}</option>)}</select></label><label style={{flex:'1 1 160px'}}>Subject<select className="input" value={browseSubject} onChange={e=>setBrowseSubject(e.target.value)}><option value="">All subjects</option>{data.options.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label style={{flex:'2 1 240px'}}>Search syllabus text or any topic<input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try a syllabus topic or any question/topic"/></label></div>{docs.isError&&<p role="alert">Could not load documents. Please retry.</p>}{docs.data?.length?<ul className="mt-4 space-y-2">{docs.data.map(d=><li key={d.id} className="border-t pt-3"><button className="underline text-left" onClick={()=>setDocId(d.id)}>{d.board_name} · {d.grade_name||'All classes'} · {d.subject_name||'All subjects'} · {d.title} · {d.academic_year}</button><p className="text-sm">{d.page_count} pages · Source: <a className="underline" href={d.source_url} target="_blank" rel="noopener noreferrer">official document ↗</a></p>{search&&d.outline?.filter(c=>c.text.toLowerCase().includes(search.toLowerCase())).slice(0,3).map((c,i)=><p className="text-sm" key={i}>Page {c.page}: {c.text}</p>)}</li>)}</ul>:<p className="mt-4">No approved syllabus documents match this search yet. Try a free-text topic in the content library: <Link className="underline" href={`/learn/library?${new URLSearchParams({q:search,board:browseBoard,grade:browseGrade})}`}>Search learning content for “{search}” →</Link>.</p>}{doc.data&&<div className="border-t mt-4 pt-4"><h3 className="font-semibold">{doc.data.title}</h3>{doc.data.downloadUrl?<a className="underline" href={doc.data.downloadUrl} target="_blank" rel="noopener noreferrer">Open PDF ↗</a>:<p>The source PDF is linked above. VidyaSetu does not redistribute this document.</p>}<ol className="mt-2 max-h-72 overflow-auto">{doc.data.outline?.slice(0,100).map((c,i)=><li key={i}>Page {c.page}: {c.text}</li>)}</ol></div>}</section>
 </div>;
}
