'use client';

import { useState } from 'react';
import { chat } from '@/services/aiService';
import { apiErrorText } from '@/utils/errors';
import type { StudentChatMessage, StudentSectionProps } from '@/types/studentPortal';
import styles from '../StudentPortal.module.css';

export default function AITutorSection({ student, notify }: StudentSectionProps) {
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [messages, setMessages] = useState<StudentChatMessage[]>([
    { role: 'assistant', content: `Namaste ${student?.name?.split(' ')[0] || 'Student'}! 🙏 I am VidyaBot. Ask me a Class ${student?.className || ''} Maths, Science, English, Hindi or Social Science question. You can ask in Hindi or English.` },
  ]);

  async function send(text: string = input): Promise<void> {
    const message = String(text || '').trim();
    if (!message || sending) return;
    const nextMessages: StudentChatMessage[] = [...messages, { role: 'user', content: message }];
    setMessages(nextMessages);
    setInput('');
    setSending(true);
    try {
      const history = nextMessages.slice(-10).map(m => ({ role: m.role, content: m.content }));
      const response = await chat(message, history.slice(0, -1));
      const answer = response?.data?.data?.response || 'I could not generate an answer. Please try again.';
      setMessages(prev => [...prev, { role: 'assistant', content: String(answer) }]);
    } catch (error: unknown) {
      notify(`⚠️ ${apiErrorText(error, 'AI Tutor is unavailable right now')}`);
      setMessages(prev => [...prev, { role: 'assistant', content: 'I had trouble connecting. Please try your question again.' }]);
    } finally {
      setSending(false);
    }
  }

  const quick = [
    'Pythagoras theorem explain karo with an example',
    'Photosynthesis step by step explain karo',
    'Solve 2x + 6 = 14 and explain each step',
    'Kharif aur Rabi crops mein difference kya hai?',
  ];

  return (
    <>
      <div className={styles.sectionHeader}>
        <div>
          <h1 className={styles.title}>🤖 AI Tutor — VidyaBot</h1>
          <div className={styles.subtitle}>Ask in Hindi or English · explanations are generated by the configured AI provider</div>
        </div>
      </div>

      <div className={styles.chat}>
        <div className={styles.chatHeader}>
          <div className={styles.botAvatar}>🤖</div>
          <div><b>VidyaBot</b><div style={{ opacity: .62, fontSize: 12 }}>● Online · NCERT-oriented learning assistant</div></div>
        </div>
        <div className={styles.chatMessages}>
          {messages.map((m, i) => (
            <div key={`${m.role}-${i}`} className={m.role === 'user' ? styles.msgUser : styles.msgAI}>{m.content}</div>
          ))}
          {sending && <div className={styles.msgAI}>Thinking…</div>}
        </div>
        <div className={styles.chatInput}>
          <input className={styles.input} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void send(); }} placeholder="Ask your doubt in Hindi or English…" />
          <button className={styles.primary} disabled={sending} onClick={() => void send()}>{sending ? '…' : 'Send ↗'}</button>
        </div>
      </div>
      <div className={styles.quickRow}>
        {quick.map(q => <button className={styles.secondary} key={q} onClick={() => void send(q)}>{q}</button>)}
      </div>
    </>
  );
}
