'use client';
import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getClasses, getSubjects, getTeachers, getTimetable, saveTimetable } from '@/services/schoolService';
import { SectionHeader, TableSkeleton } from '@/components/ui/index';
import useAuthStore from '@/store/authStore';
import toast from 'react-hot-toast';

const DAYS=['MON','TUE','WED','THU','FRI','SAT'];
const DAY={MON:'Mon',TUE:'Tue',WED:'Wed',THU:'Thu',FRI:'Fri',SAT:'Sat'};
const err=e=>e?.response?.data?.error?.message||e?.message||'Failed to save timetable';
const newRow=()=>({day:'MON',periodNumber:1,startTime:'08:00',endTime:'08:40',subjectCode:'',teacherId:'',roomNumber:'',isBreak:false,breakLabel:''});

export default function SchoolTimetablePage(){
 const {user}=useAuthStore();const canEdit=['SCHOOL_ADMIN','SUPER_ADMIN'].includes(user?.role);const qc=useQueryClient();const [classId,setClassId]=useState('');const [editing,setEditing]=useState(false);const [rows,setRows]=useState([]);
 const classesQ=useQuery({queryKey:['school-classes'],queryFn:()=>getClasses().then(r=>r.data.data||[])});const teachersQ=useQuery({queryKey:['school-teachers'],queryFn:()=>getTeachers().then(r=>r.data.data||[])});const subjectsQ=useQuery({queryKey:['school-subjects'],queryFn:()=>getSubjects().then(r=>r.data.data||[])});
 const q=useQuery({queryKey:['school-timetable',classId],queryFn:()=>getTimetable(classId).then(r=>r.data.data||[]),enabled:!!classId});
 useEffect(()=>{if(!q.data)return;setRows(q.data.map(p=>({day:p.day,periodNumber:p.period_number,startTime:String(p.start_time).slice(0,5),endTime:String(p.end_time).slice(0,5),subjectCode:p.subject_code||'',teacherId:p.teacher_id||'',roomNumber:p.room_number||'',isBreak:!!p.is_break,breakLabel:p.break_label||''})));},[q.data]);
 const save=useMutation({mutationFn:()=>saveTimetable(classId,rows.map(r=>({...r,periodNumber:Number(r.periodNumber),teacherId:r.teacherId||null,subjectCode:r.subjectCode||null}))),onSuccess:async()=>{toast.success('Timetable saved');setEditing(false);await qc.invalidateQueries({queryKey:['school-timetable',classId]});},onError:e=>toast.error(err(e))});
 const periods=q.data||[];const byDay=useMemo(()=>Object.fromEntries(DAYS.map(d=>[d,periods.filter(x=>x.day===d).sort((a,b)=>a.period_number-b.period_number)])),[periods]);const periodNumbers=[...new Set(periods.map(x=>x.period_number))].sort((a,b)=>a-b);
 function change(i,k,v){setRows(x=>x.map((r,j)=>j===i?{...r,[k]:v}:r));}
 function add(){const r=newRow();r.periodNumber=rows.length?Math.min(12,Math.max(...rows.map(x=>Number(x.periodNumber)||0))+1):1;setRows(x=>[...x,r]);setEditing(true);}
 return <div className="animate-fade-up">
  <SectionHeader title="🗓️ Timetable" sub={canEdit?'Build class schedules with Teacher conflict checks':'View the School timetable'}>{classId&&canEdit&&<button className="btn-primary" onClick={()=>setEditing(v=>!v)}>{editing?'View Timetable':'Edit Timetable'}</button>}</SectionHeader>
  <div className="card mb-5"><select className="input select w-full max-w-xs" value={classId} onChange={e=>{setClassId(e.target.value);setEditing(false)}}><option value="">Select a class</option>{(classesQ.data||[]).map(c=><option key={c.id} value={c.id}>Class {c.class_name}-{c.section}</option>)}</select></div>
  {!classId&&<div className="card text-center py-12"><div className="text-4xl mb-2">🗓️</div><b>Select a class to view its timetable</b></div>}
  {classId&&q.isLoading&&<TableSkeleton rows={6} cols={7}/>} 
  {classId&&!q.isLoading&&editing&&canEdit&&<div className="card"><div className="flex justify-between items-center mb-4"><h3 className="font-display font-bold" style={{color:'var(--navy)'}}>Timetable Editor</h3><button className="btn-ghost text-xs" onClick={add}>+ Add Period</button></div><div className="space-y-2">{rows.map((r,i)=><div key={i} className="grid md:grid-cols-[90px_85px_95px_95px_1fr_1fr_110px_80px] gap-2 items-center p-2 rounded-xl" style={{background:'#F7F8FA'}}><select className="input select" value={r.day} onChange={e=>change(i,'day',e.target.value)}>{DAYS.map(d=><option key={d}>{d}</option>)}</select><input type="number" min="1" max="12" className="input" value={r.periodNumber} onChange={e=>change(i,'periodNumber',Number(e.target.value))}/><input type="time" className="input" value={r.startTime} onChange={e=>change(i,'startTime',e.target.value)}/><input type="time" className="input" value={r.endTime} onChange={e=>change(i,'endTime',e.target.value)}/>{r.isBreak?<input className="input" placeholder="Break label" value={r.breakLabel} onChange={e=>change(i,'breakLabel',e.target.value)}/>:<select className="input select" value={r.subjectCode} onChange={e=>change(i,'subjectCode',e.target.value)}><option value="">Subject</option>{(subjectsQ.data||[]).map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select>}{r.isBreak?<div/>:<select className="input select" value={r.teacherId} onChange={e=>change(i,'teacherId',e.target.value)}><option value="">Teacher</option>{(teachersQ.data||[]).filter(t=>t.status==='ACTIVE').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}<label className="text-xs flex gap-1 items-center"><input type="checkbox" checked={r.isBreak} onChange={e=>change(i,'isBreak',e.target.checked)}/> Break</label><button className="text-xs font-bold" style={{color:'#C62828'}} onClick={()=>setRows(x=>x.filter((_,j)=>j!==i))}>Remove</button></div>)}</div>{!rows.length&&<div className="py-8 text-center" style={{color:'var(--slate)'}}>No periods. Add the first period to build this timetable.</div>}<button className="btn-primary mt-4" disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving…':'Save Timetable'}</button></div>}
  {classId&&!q.isLoading&&!editing&&<div className="card overflow-x-auto">{!periods.length?<div className="text-center py-12"><div className="text-4xl mb-2">🗓️</div><b>No timetable configured yet</b>{canEdit&&<div><button className="btn-primary mt-4" onClick={()=>{setRows([]);setEditing(true);add();}}>Create Timetable</button></div>}</div>:<table className="w-full text-sm" style={{minWidth:700}}><thead><tr><th className="p-2 text-left" style={{background:'#F8F9FC'}}>Period</th>{DAYS.map(d=><th key={d} className="p-2 text-center" style={{background:'#F8F9FC'}}>{DAY[d]}</th>)}</tr></thead><tbody>{periodNumbers.map(n=><tr key={n}><td className="p-2" style={{borderBottom:'1px solid var(--border)'}}><b>{n}</b><div className="text-xs" style={{color:'var(--slate)'}}>{periods.find(p=>p.period_number===n)?.start_time?.slice(0,5)}–{periods.find(p=>p.period_number===n)?.end_time?.slice(0,5)}</div></td>{DAYS.map(d=>{const p=byDay[d]?.find(x=>x.period_number===n);return <td key={d} className="p-2 text-center" style={{borderBottom:'1px solid var(--border)'}}>{p?p.is_break?<span className="text-xs" style={{color:'var(--slate)'}}>— {p.break_label||'Break'} —</span>:<div className="rounded-lg px-2 py-1.5 text-xs" style={{background:'var(--saffron-pale)',color:'var(--navy)'}}><b>{p.subject||p.subject_code}</b><div style={{color:'var(--slate)'}}>{p.teacher_name||'Unassigned'}</div></div>:'—'}</td>})}</tr>)}</tbody></table>}</div>}
 </div>;
}
